fixed email validation on dashboards
zebrunner/reporting-ui pull request #215
Opened 2019-10-09 07:35 UTC by Ageenkooo

fixes #1779

2019-10-18 10:45 UTC, danymill requested changes

2019-10-18 10:45 UTC, danymill commented on client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js
> +                    return rs.data.results.filter(searchFilter(user)).filter((user) => user.email);
Please refactor `searchFilter` and `querySearch`

2019-10-21 09:01 UTC, danymill requested changes

2019-10-21 09:01 UTC, danymill commented on client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js
> +            return;
Don't allow to add invalid email instead of displaying error on sent action

2019-10-21 09:39 UTC, Ageenkooo commented
@danymill improved; fixed case for number input

2019-10-21 09:54 UTC, danymill requested changes

2019-10-21 09:54 UTC, danymill commented on client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js
> +        $scope.users.push(user);
What will happen if `currentUser` is a `Number`?

2019-10-21 09:54 UTC, danymill commented on client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js
> +            if (typeof currentUser === 'string') {
Redundant checking

2019-10-21 10:12 UTC, danymill approved these changes

2019-10-21 10:13 UTC, merged