Feature/logs switcher
zebrunner/reporting-ui pull request #357
Opened 2020-02-11 14:08 UTC by MitskevichVS

### Add ###
1. Sessions/Tests switcher
### Screenshot ###
![image](https://user-images.githubusercontent.com/47656449/74243572-11578880-4cf1-11ea-9f56-0c4041382418.png)

2020-02-12 06:52 UTC, danymill requested changes

2020-02-12 06:52 UTC, danymill commented on client/app/app.module.js
> +
redundant empty line

2020-02-12 06:52 UTC, danymill commented on client/app/shared/sessions-switcher/sessions-switcher.component.scss
> +
redundant empty line

2020-02-12 07:33 UTC, MitskevichVS commented on client/app/app.module.js
> +
fixed

2020-02-12 07:34 UTC, MitskevichVS commented on client/app/shared/sessions-switcher/sessions-switcher.component.scss
> +
fixed

2020-02-14 07:28 UTC, danymill requested changes

2020-02-14 07:28 UTC, danymill commented on client/app/shared/sessions-switcher/sessions-switcher.component.scss
> +    @media screen and (max-width: $breakpoint-mobile - 1) {
please use `$md-screen-phone` instead of old `$breakpoint-mobile`

2020-02-14 07:28 UTC, danymill commented on client/app/shared/sessions-switcher/sessions-switcher.component.html
> +    </div>
Incorrect tabulation

2020-02-14 07:28 UTC, danymill commented on client/app/containers/tests-runs/tests-runs.html
> +            on-switcher-change="$ctrl.onViewChange($value)" is-switcher-disabled="$ctrl.isUserParamSaving"></tests-runs-filter>
incorrect tabulation

2020-02-14 08:42 UTC, danymill approved these changes

2020-02-14 09:18 UTC, merged