Fix (ZEB-728) username validation
zebrunner/reporting-ui pull request #383
Opened 2020-03-05 09:16 UTC by MitskevichVS

2020-03-05 17:51 UTC, danymill requested changes

2020-03-05 17:51 UTC, danymill commented on client/app/_user/profile.html
> +                            ng-minlength="$ctrl.getValidationValue('name', 'minlength')"
Please, use one-time binding `::` (see details [here](https://docs.angularjs.org/guide/expression))

2020-03-05 17:51 UTC, danymill commented on client/app/_user/profile.html
> +                            ng-pattern="/^[a-zA-Z]+[a-zA-Z.-\d]+$/"
Move pattern into service as well

2020-03-05 17:51 UTC, danymill commented on client/app/_user/profile.html
> +                            ng-pattern="/^[a-zA-Z]+[a-zA-Z.-\d]+$/"
See comments above

2020-03-05 17:51 UTC, danymill commented on client/app/_users/modals/create_modal.html
> +                            ng-minlength="UtilService.getValidationValue('name', 'minlength')"
See comments above

2020-03-05 17:51 UTC, danymill commented on client/app/_users/modals/create_modal.html
> +                            ng-minlength="UtilService.getValidationValue('name', 'minlength')"
See comments above

2020-03-05 17:51 UTC, danymill commented on client/app/_users/modals/edit_modal.html
> +                            ng-pattern="/^[a-zA-Z]+[a-zA-Z.-\d]+$/"
See comments above

2020-03-05 17:51 UTC, danymill commented on client/app/_users/modals/edit_modal.html
> +                            ng-minlength="UtilService.getValidationValue('name', 'minlength')"
See comments above

2020-03-06 09:06 UTC, MitskevichVS commented on client/app/_user/profile.html
> +                            ng-minlength="$ctrl.getValidationValue('name', 'minlength')"
fixed

2020-03-06 09:06 UTC, MitskevichVS commented on client/app/_user/profile.html
> +                            ng-pattern="/^[a-zA-Z]+[a-zA-Z.-\d]+$/"
fixed

2020-03-06 09:07 UTC, MitskevichVS commented on client/app/_user/profile.html
> +                            ng-pattern="/^[a-zA-Z]+[a-zA-Z.-\d]+$/"
fixed

2020-03-06 09:07 UTC, MitskevichVS commented on client/app/_users/modals/create_modal.html
> +                            ng-minlength="UtilService.getValidationValue('name', 'minlength')"
fixed

2020-03-06 09:07 UTC, MitskevichVS commented on client/app/_users/modals/edit_modal.html
> +                            ng-pattern="/^[a-zA-Z]+[a-zA-Z.-\d]+$/"
fixed

2020-03-06 09:07 UTC, MitskevichVS commented on client/app/_users/modals/create_modal.html
> +                            ng-minlength="UtilService.getValidationValue('name', 'minlength')"
fixed

2020-03-06 09:07 UTC, MitskevichVS commented on client/app/_users/modals/edit_modal.html
> +                            ng-minlength="UtilService.getValidationValue('name', 'minlength')"
fixed

2020-03-06 10:43 UTC, danymill requested changes

2020-03-06 10:43 UTC, danymill commented on client/app/_services/util.service.js
> +            return validationsArray.find(item => item.name === propName).value || null;
if an item with `propName` is not found your code will throw an error

2020-03-06 11:52 UTC, danymill approved these changes

2020-03-06 11:52 UTC, merged