Fix (ZEB-822) error message
zebrunner/reporting-ui pull request #384
Opened 2020-03-05 09:48 UTC by MitskevichVS

2020-03-05 18:02 UTC, danymill requested changes

2020-03-05 18:02 UTC, danymill commented on client/app/_services/dashboard.service.js
> +        };
remove trailing semicolon after function declaration

2020-03-06 07:39 UTC, MitskevichVS commented on client/app/_services/dashboard.service.js
> +    function DashboardService($httpMock,
fixed

2020-03-06 07:39 UTC, MitskevichVS commented on client/app/_services/dashboard.service.js
> +        };
fixed

2020-03-06 10:51 UTC, danymill approved these changes

2020-03-06 10:51 UTC, merged